services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    ports:
      - "3000:3000" # Backend serves everything
    command: >
      sh -c "cd /app/frontend && npm install && npm run build:watch &
             cd /app/backend && npm install && nodemon server.js"
