services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
    ports:
      - "3000:3000"  # Backend serves everything